language: python
branches:
    only:
      - master
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r test-requirements.txt
  - pip install tox
  - pip install coveralls
script:
  - make test doc quality
after_success:
  - coveralls
env:
  - TOXENV=djangoNA
  - TOXENV=django14
  - TOXENV=django15
  - TOXENV=django16
  - TOXENV=django17
  - TOXENV=django18
